# Generated by Django 3.0.6 on 2020-12-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Текст задачи'),
        ),
    ]
